__title__ = "PyDVPL"
__description__ = "A CLI Tool Coded In Python3 To Convert WoTB ( Dava ) SmartDLC DVPL File Based On LZ4 High Compression."
__version__ = "0.7.0"
__date__ = "2024-03-14"
__author__ = "RifsxD"
__repo__ = "https://github.com/rifsxd/pydvpl"